//
// Created by jefflee on 2023/9/1.
//

#ifndef PLAYERSDK_MEDIACACHE_SOURCE_COMMON_COMMON_H_
#define PLAYERSDK_MEDIACACHE_SOURCE_COMMON_COMMON_H_

static const char *HTTP_PROTOCOL = "http://";
static const char *LOCAL_PROXY = "127.0.0.1";

#endif //PLAYERSDK_MEDIACACHE_SOURCE_COMMON_COMMON_H_
